### ISSUE TITLE
"developer" from the details() method is not working

### ISSUE THREAD

**Issue by Thug0416** [danieliu/play-scraper#11]
Hi, 
I already had contact with daniel and he told me to put this issue here.
I am using:
- windows 10 operating system
- pyhon 3.7.0
- play-scraper 0.2.4 

The rest seems to work fine. Atleast for the developer() method.

Code:
app_id = "com.igg.android.lordsmobile"
details = play_scraper.details(app_id)
print(details["developer"])

It keeps giving me Google Commerce Ltd for every app_id I put in. 
The Google Commerce Ltd can been found on the bottom of each app page. 

Offered By
Google Commerce Ltd

Maybe this has something to do with it?

**Comment by danieliu** [comment]
![screen shot 2018-07-22 at 12 56 49 am 1](https://user-images.githubusercontent.com/8889973/43043511-373f7a52-8d4a-11e8-84fb-ab7262fbb553.png)

I don't see `Google Commerce Ltd` under Offered By. Do you have a screenshot?

**Comment by Thug0416** [comment]
I am not kidding. Literally every app.







2018-07-22 10:00 GMT+02:00 Daniel Liu <notifications@github.com>:

**Comment by danieliu** [comment]
If every app shows `Google Commerce Ltd` under `Offered By` when you go to their page in the browser, then this less so a `play-scraper` specific issue, as it just scrapes whatever is on the page.

I had a feeling that it might be a country-specific thing, and it seems like I'm right. Unfortunately, the option to specify the geolocation or language query parameter doesn't exist yet, but would allow a workaround for this specific issue.

**Comment by Thug0416** [comment]
there is another issue:
this one is code-specific. some developer-id's are not working. for
example  when i give as "7706714075287612145" developer_id in the
developer() method it goes to:

https://play.google.com/store/apps/developer?id=7706714075287612145

this  however wont work because the actual url is:

https://play.google.com/store/apps/dev?id=7706714075287612145

notice the difference(dev instead of developer) in the url

2018-07-22 17:05 GMT+02:00 Daniel Liu <notifications@github.com>:

**Comment by Thug0416** [comment]
how can i  work around this? use vpn?


2018-07-22 17:05 GMT+02:00 Daniel Liu <notifications@github.com>:

**Comment by Thug0416** [comment]
dude  i used vpn no w it works!!!!tnx for  the  trouble friend

2018-07-22 17:46 GMT+02:00 Abdulkader Abdullah <crew.gladiator@gmail.com>:

**Comment by Thug0416** [comment]
the developer/dev problem still occurs

2018-07-22 18:00 GMT+02:00 Abdulkader Abdullah <crew.gladiator@gmail.com>:

**Comment by danieliu** [comment]
The `.developer()` method takes in the developer name, not the developer id. This is because the `/dev?id=<developer_id>` page doesn't display a full list of apps (it's hidden under another click into another `collection` page), while the `/developer?id=<developer_name>` has a full list.

This is a good thing to note, though, I'll add an exception or some sort of error message / logging so it doesn't accept developer ids.

**Comment by Thug0416** [comment]
So i have to pass in “developer” instead of “developer_id”?

Verzonden vanuit Mail voor Windows 10

Van: Daniel Liu
Verzonden: zondag 22 juli 2018 18:43
Aan: danieliu/play-scraper
CC: Thug0416; Author
Onderwerp: Re: [danieliu/play-scraper] "developer" from the details() method isnot working (#11)

The .developer() method takes in the developer name, not the developer id. This is because the /dev?id=<developer_id> page doesn't display a full list of apps (it's hidden under another click into another collection page), while the /developer?id=<developer_name> has a full list.
This is a good thing to note, though, I'll add an exception or some sort of error message / logging so it doesn't accept developer ids.

**Comment by danieliu** [comment]
> So i have to pass in “developer” instead of “developer_id”?

Yes, pass in the `developer` that you receive, rather than `developer_id`. This isn't extensively tested, especially with the wide variety of possible developer name strings, so definitely please create another issue if you run into any problems.

**Comment by Thug0416** [comment]
I get less results than  when i pass the
"developer_id"....................................

2018-07-22 18:46 GMT+02:00 Daniel Liu <notifications@github.com>:

**Comment by Thug0416** [comment]
noo noo sorry!! sorry! its doing better thanks...

sorry for being a pain in the ass

2018-07-22 19:08 GMT+02:00 Abdulkader Abdullah <crew.gladiator@gmail.com>:

**Comment by danieliu** [comment]
In [0.3.2](https://github.com/danieliu/play-scraper/releases/tag/v0.3.2), you can now specify a `gl` keyword argument now for the country, or leave it (defaults to `us`).

e.g.
```
>>> import play_scraper
>>> play_scraper.details('com.igg.android.lordsmobile', gl='us')
```

This fixes the `Google Commerce Ltd` issue that you would see if `gl='be'` for Belgium, for example.
