### ISSUE TITLE
Do it support Python3.7

### ISSUE THREAD

**Issue by 1074736711** [danieliu/play-scraper#13]
when I invoke 'python3 -m pip install play_scraper', it say:
`command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-cj268d40/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-mzwfg42a/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-cj268d40/lxml/`

**Comment by danieliu** [comment]
This should be fixed now. `lxml` was pinned to the wrong version in `setup.py`. Thanks for pointing this out!
