### ISSUE TITLE
problem installing with install-option

### ISSUE THREAD

**Issue by lorenzoinno** [danieliu/play-scraper#15]
Hello,
trying to install the package:
pip install play-scraper --install-option="--prefix=/airflow"

is causing this error:

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3jPoyb/play-scraper/setup.py", line 10, in <module>
        with open('README.md', 'r', 'utf-8') as f:
      File "/usr/lib64/python2.7/codecs.py", line 881, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: 'README.md'

how can we solve?

P.S. installing without the option works fine

thanks,
Lorenzo

**Comment by danieliu** [comment]
This should be fixed in `play-scraper==0.4.2`. I added a `MANIFEST.in`, and the prefix option should work properly now.

If you run into any other problems, please open a new issue!
