### ISSUE TITLE
output format

### ISSUE THREAD

**Issue by A-AFTAHI** [danieliu/play-scraper#18]
Hi, thanks for this cool scraper. 
I just want to mention that the output data is not in a clean json format. when i used python json parsing library it shows error. 

Thanks!

**Comment by danieliu** [comment]
Can you give an example, or steps to reproduce this?

**Comment by masroore** [comment]
before json dumping the result, delete the `description_html` property (type: bytes) from the object
or use `pprint()`

**Comment by danieliu** [comment]
I'm unable to reproduce this. The following works fine:

```python
import json
import play_scraper

data = play_scraper.details('com.android.chrome')
print(data)
print(json.dumps(data))
```

Feel free to re-open if the issue still persists.
