### ISSUE TITLE
Developer field not working for play_scraper.collection() with gl<>'us' and detailed=True 

### ISSUE THREAD

**Issue by tamha** [danieliu/play-scraper#21]
Edit : not a problem with the library, the webpage itself is wrong when using a non default gf. So I guess nothing you can do about it (by the way thanks for this very useful library). Workaround I used : going through the list of apps scraped a second time using gl='us'.
When using play_scraper.collection() with gl<>'us' (ex:gl='fr') and with detailed=True, the developer field is always 'Google Commerce Ltd'.
Developer field is correct when using default gl.

**Comment by tamha** [comment]
Edit : not a problem with the library, the webpage itself is wrong when using a non default gf. So I guess nothing you can do about it (by the way thanks for this very useful library). Workaround I used : going through the list of apps scraped a second time using gl='us'.

**Comment by danieliu** [comment]
Oh, this is what happened in #11, which prompted me to add the `hl` and `gl` params.

However, I did a quick look and those language and country parameters aren't actually included in the app detail requests following a list request, so those results may end up different than expected. I'll get a fix for that if I get the chance.
