### ISSUE TITLE
Error running simple example. Help please.

### ISSUE THREAD

**Issue by rjalexa** [danieliu/play-scraper#26]
```
import play_scraper
print play_scraper.details('com.android.chrome')
```

```
File "<ipython-input-8-60b6c1359646>", line 2
    print play_scraper.details('com.android.chrome')
                     ^
SyntaxError: invalid syntax

```
Running on Mac OS with python:
3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by danieliu** [comment]
Looks like you're running Python 3, where `print` is a function.
You'll need to do `print(play_scraper.details('com.android.chrome'))`.

I'll update the readme and examples to be Python version agnostic.

**Comment by rjalexa** [comment]
Thank you very very much!
