### ISSUE TITLE
Improve requirements.txt

### ISSUE THREAD

**Issue by maaaaz** [danieliu/play-scraper#27]
Hello @danieliu,

First, thank you for that great module.
Then, could you replace the `==` of the `requirements.txt` by `>=` ? Unless your module does not these exact versions, I think it can be compatible with newer versions.

Cheers !

**Comment by danieliu** [comment]
Updated the `install_requires` in 17cc5a6674a47d07469a2fe30e4ea8a8f95b04e4.
Feel free to open a new issue if you encounter any problems.
