### ISSUE TITLE
How can I list topselling_paid or topselling_free?

### ISSUE THREAD

**Issue by harunresitc** [danieliu/play-scraper#29]
How can I list topselling_paid or topselling_free?
Links:
https://play.google.com/store/apps/category/GAME/collection/topselling_paid
https://play.google.com/store/apps/category/GAME/collection/topselling_free

**Comment by danieliu** [comment]
The [README](https://github.com/danieliu/play-scraper#collection) has a section and example for collections.

```python
import play_scraper

data = play_scraper.collection('TOP_FREE', 'GAME_ACTION')
print(data)
```

I'll update the category list to include `GAME` as an accepted option since that seems to be missing.
