### ISSUE TITLE
Variable and function names are the same.

### ISSUE THREAD

**Issue by rchatterjee** [danieliu/play-scraper#3]
https://github.com/danieliu/play-scraper/blob/6059c472571641a568e810c96309af530bd77330/play_scraper/api.py#L25

I am getting `RecursionError: maximum recursion depth exceeded` error. I think you if you change the variable name to something else, that will fix the issue. Thanks.

**Comment by danieliu** [comment]
Seems like a different issue. I think this is more related to `requests` and SSL as mentioned in #7 . Will take a look into testing across python versions and also `requests`. Might need to use `requests[security]`.
