### ISSUE TITLE
IndexError: list index out of range while getting collections

### ISSUE THREAD

**Issue by rajcanius** [danieliu/play-scraper#34]
**Describe the bug**
While requesting NEW_FREE collection I get IndexError exception:

  File ".../python2.7/site-packages/play_scraper/api.py", line 41, in collection
    return s.collection(collection, category, **kwargs)
  File ".../python2.7/site-packages/play_scraper/scraper.py", line 134, in collection
    for app_card in soup.select('div[data-uitype="500"]')]
  File ".../python2.7/site-packages/play_scraper/utils.py", line 358, in parse_card_info
    developer_id = dev_soup.attrs['href'].split('=')[1]
IndexError: list index out of range

**To Reproduce**
run play_scraper.collection(collection='NEW_FREE',results=100,page=0,gl='us')

**Expected behavior**
Should receive list of app metadata from specified Chart in Google Play

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: [Linux Ubuntu 12.04.5 LTS, Precise Pangolin, MacOS Mojave 10.14.3]
 - Python Version: [2.7.3, 2.7.10]
 - play_scraper Version: [0.5.2: 2019-01-19]

**Additional context**
It seems, like the scraper is getting wrong response from Google Play and cannot parse it correctly.

**Comment by rajcanius** [comment]
Upon better inspection I have realised, there is this exception because (at least) one app in the list has no developer name (not sure how is this possible).

Namely, it is app https://play.google.com/store/apps/details?id=org.selfie.beauty.camera.pro
(notice, that there is no developer name, 'Photography' is the category of the app)

Same thing is noticeable in the list view - https://play.google.com/store/apps/collection/topselling_new_free?gl=us

I'd suggest adding checks, wether fields are actually splittable.

**Comment by danieliu** [comment]
Should be fixed by 27bca887ec07386ee58cd8bcd79f50eddabf8497.
