### ISSUE TITLE
Exception Thrown by play-scraper.details Method

### ISSUE THREAD

**Issue by torind** [danieliu/play-scraper#37]
**Describe the bug**
Attempting to run the example described in the README:
`print(play_scraper.details('com.android.chrome'))`
returns a AttributeError.

**To Reproduce**
```
import play_scraper
print(play_scraper.details('com.android.chrome'))
```

**Screenshots**
![image](https://user-images.githubusercontent.com/21142230/54958307-84f27a80-4f12-11e9-804d-249ee85598ef.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.1
 - Python Version: 3.6.5
 - play_scraper Version: 0.5.3

**Additional context**
Seems related to Issue #2

**Comment by fernandoarrj** [comment]
I have the same issue.
Solved by change the line 311 on file utils.py :

**Before:**
additional_info_data = parse_additional_info(
    soup.select_one('.xyOfqd'))

**Now**
additional_info_data = parse_additional_info(
    soup.select_one('.wSaTQd'))
