### ISSUE TITLE
In collection few categories are not managed

### ISSUE THREAD

**Issue by priyamshah112** [danieliu/play-scraper#4]
The categories "APP_WALLPAPER","TRANSPORTATION","MEDIA_AND_VIDEO","APP_WIDGETS" have no collection defined for them as their url are not there in google play store.

Error:HTTPError: 404 Client Error: Not Found for url: https://play.google.com/store/apps/category/APP_WALLPAPER/collection/movers_shakers

**Comment by danieliu** [comment]
Updated `CATEGORIES` list in `lists.py` to the latest available categories. Also added a new categories api to scrape the list of categories.
