### ISSUE TITLE
Wrong selector beautiful soup

### ISSUE THREAD

**Issue by general03** [danieliu/play-scraper#44]
**Describe the bug**
The scraper crash because selector css not found

**To Reproduce**
` play_scraper.details('whatever_id')`
>> 'NoneType' object has no attribute 'attrs'

**Expected behavior**
No crash when selector not found

**Desktop**
 - OS: Win 7
 - Python Version 3.7
 - play_scraper Version 0.5.4

The issue is on utils.py line 241
`soup.select_one('.dQrBL img.ujDFqe')`

**Comment by danieliu** [comment]
Duplicate of #42.

**Comment by danieliu** [comment]
Fixed by #43
