### ISSUE TITLE
save data to csv file

### ISSUE THREAD

**Issue by Achuet414** [danieliu/play-scraper#46]
Really it is great post. Thank you so much.
 As I am very new to python , I am unable to save the output to csv file for filtering based on number of installations.

**Comment by AbdulghaniAhlam** [comment]
Firstly, you must save your output into a list and then you can read from the list to excel file. I used this code before:
import xlsxwriter
workbook = xlsxwriter.Workbook('ArabicApps.xlsx')
worksheet = workbook.add_worksheet()


row = 1
col = 0
for entry in ItemList:
    print(entry)       
    worksheet.write_string  (row, col,entry)
    row += 1

workbook.close()

**Comment by Achuet414** [comment]
Thank You very much for your reply. I am trying the below code.
`import play_scraper
import xlsxwriter

print(play_scraper.collection(
        collection='TOP_GROSSING',
        category='GAME_RACING',
        results=50,
        page=10))

workbook = xlsxwriter.Workbook('ArabicApps.xlsx')
worksheet = workbook.add_worksheet()

row = 1
col = 0
for entry in ItemList:
    print(entry)
worksheet.write_string (row, col,entry)
row += 1

workbook.close()
`

> Traceback (most recent call last):
  File "C:\Users\System Admin\Desktop\play.py", line 15, in <module>
    for entry in ItemList:
NameError: name 'ItemList' is not defined



Could you please tell me , where i am doing wrong

**Comment by AbdulghaniAhlam** [comment]
instead of print the output of apps' info you must define ItemList like this 

ItemList = play_scraper.collection(
collection='TOP_GROSSING',
category='GAME_RACING',
results=50,
page=10)

**Comment by danieliu** [comment]
This is not something we'll be supporting - it should be fairly straightforward to do this yourself, as mentioned above, as the data is returned in a standard format (JSON).
