### ISSUE TITLE
'NoneType' object has no attribute 'attrs'

### ISSUE THREAD

**Issue by kushalkrip** [danieliu/play-scraper#48]
It gives an error on line 240, 
`icon = (soup.select_one('.dQrBL img.ujDFqe')`
On replacing it with : `icon = (soup.select_one ('. XSyT2c `img.T75of')` as suggested in Issue 42, the error was still not resolved.
Kindly suggest on what should be done to resolve this issue.
--

**Comment by danieliu** [comment]
Duplicate of #42

**Comment by danieliu** [comment]
Fixed by #43
