### ISSUE TITLE
Getting similar apps returns empty list

### ISSUE THREAD

**Issue by woutwoot** [danieliu/play-scraper#49]
**Describe the bug**
Getting similar apps is broken, it does not return any apps. This also fails in the unit tests with `AssertionError: 0 not greater than 0`

**To Reproduce**
Easiest way is to run the unit tests.

**Expected behavior**
The tests do not fail and similar apps are returned when using the method.

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Python Version 3.7
 - play_scraper Version 0.5.5

**Comment by NikolaiSachok** [comment]
Looks like Google changed or obfuscated css attributes names the plugin uses to get similar apps details from html response.
