### ISSUE TITLE
categories returns empty result

### ISSUE THREAD

**Issue by xulifan** [danieliu/play-scraper#59]
**Describe the bug**
When calling categories, it returns empty result

**To Reproduce**

>>> import play_scraper
>>> play_scraper.__version__
'0.5.5'
>>> play_scraper.categories()
{}

**Desktop (please complete the following information):**
 - Ubuntu 16
 - Python 3.5.2
 - play_scraper Version 0.5.5

**Comment by nevelis** [comment]
Confirmed in both 0.4.2 and 0.5.5 on Python 3.7.1 on Linux & Mac.
