### ISSUE TITLE
suddenly fires error 'App not found (404)' on request

### ISSUE THREAD

**Issue by 0xBB2B** [danieliu/play-scraper#60]
**Describe the bug**
I implemented this module in my service and worked well.
recently, module fires 'App not found(404)' error 70~80% of request.
strange thing is request success sometime.
that error on category only page

**To Reproduce**
import play_scraper
print(play_scraper.collection(
        collection='TOP_GROSSING',
        category='GAME',
        gl='jp',
        results=10,
        page=0))

**Error message**
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://play.google.com/store/apps/category/GAME/collection/topgrossing?hl=en&gl=jp

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Python Version 3.7.4
 - play_scraper Version 0.5.5

**Comment by xulifan** [comment]
Same issue here. I believe GooglePlay changed its links.

**Comment by nellqa** [comment]
Hi all,
Thanks for creating this extremely useful package. 
I have the same issue described by the guys above. Is it possible to give some info on expected fix date?
Thanks!

**Comment by AnikaTabassum** [comment]
facing same problem. how did you guys solve it?

**Comment by ayubn** [comment]
> 
> 
> **Describe the bug** I implemented this module in my service and worked well. recently, module fires 'App not found(404)' error 70~80% of request. strange thing is request success sometime. that error on category only page
> 
> **To Reproduce** import play_scraper print(play_scraper.collection( collection='TOP_GROSSING', category='GAME', gl='jp', results=10, page=0))
> 
> **Error message** requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://play.google.com/store/apps/category/GAME/collection/topgrossing?hl=en&gl=jp
> 
> **Desktop (please complete the following information):**
> 
>     * OS: macOS 10.14.6
> 
>     * Python Version 3.7.4
> 
>     * play_scraper Version 0.5.5

hi, did u solve this issue ? if yes can u please help me tooo
