### ISSUE TITLE
Items in resulting dict are BeautifulSoup entities

### ISSUE THREAD

**Issue by mpyrev** [danieliu/play-scraper#8]
Items in resulting dict are BeautifulSoup entities, not primitives as user may think after looking on examples.
I'm using this lib with multiprocessing. And I found out that results cannot be pickled by multiprocessing's map (RecursionError). I propose converting values in resulting dict into true primitives.

**Comment by danieliu** [comment]
Pushed [v0.2.2](https://github.com/danieliu/play-scraper/releases/tag/v0.2.2) that should fix the general cases of this by using `.text` instead of `.string`, along with doing `.strip()` to basically coerce to unicode. If you run into any other problems, feel free to open up a new issue.
