### ISSUE TITLE
Play Store itself

### ISSUE THREAD

**Issue by jyxjjj** [danieliu/play-scraper#94]
**Is your feature request related to a problem? Please describe.**
```
>>> print(play_scraper.details('com.android.vending'))
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
```

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/play_scraper/scraper.py", line 82, in details
    response = send_request('GET', url, params=self.params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/play_scraper/utils.py", line 121, in send_request
    response.raise_for_status()
  File "/opt/homebrew/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://play.google.com/store/apps/details?id=com.android.vending&hl=en&gl=us

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/play_scraper/api.py", line 22, in details
    return s.details(app_id)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/play_scraper/scraper.py", line 85, in details
    raise ValueError('Invalid application ID: {app}. {error}'.format(
ValueError: Invalid application ID: com.android.vending. 404 Client Error: Not Found for url: https://play.google.com/store/apps/details?id=com.android.vending&hl=en&gl=us
```

**Comment by jyxjjj** [comment]
> its not possible, even on the web client:
> 
> 
> 
> https://play.google.com/store/apps/details?id=com.android.vending

Oh I found, but I don't know why ApkMirror and ApkDownloader can get it.
Seems that there is something like protocol, can download it after login.
I think there's a way to get its update.

**Comment by hr8** [comment]
yes, you can download the APK, but you cannot return details for the app.

the details endpoint is not the same as the delivery endpoint.

**Comment by jyxjjj** [comment]
Thank you for your information, but I'm new to this repository, maybe due to my negligence, I don't see other ways to download this apk, can you tell me if this repository is available for downloading this apk?

**Comment by hr8** [comment]
https://github.com/hr8/googleplay/issues/4
